{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-media
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: jellyfin
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.persistence.media.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.persistence.media.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.persistence.media.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.media.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
  {{- if .Values.persistence.media.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.media.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.media.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.media.dataSource "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.persistence.media "global" .Values.global) | nindent 2 }}
{{- end -}}
